name: Newman Run

on:
  pull_request:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: BAAS_Account_Enquiry.postman_collection.json
          environment: BAAS_Environment.postman_environment.json
